#!/usr/bin/env python
alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ. :/"

print(" |" + alpha)
print("-" * len(alpha))
for i in range(len(alpha)):
    print(alpha[i] + "|" + alpha[i:] + alpha[:i])

#  |ABCDEFGHIJKLMNOPQRSTUVWXYZ. :/
# ------------------------------
# A|ABCDEFGHIJKLMNOPQRSTUVWXYZ. :/
# B|BCDEFGHIJKLMNOPQRSTUVWXYZ. :/A
# C|CDEFGHIJKLMNOPQRSTUVWXYZ. :/AB
# D|DEFGHIJKLMNOPQRSTUVWXYZ. :/ABC
# E|EFGHIJKLMNOPQRSTUVWXYZ. :/ABCD
# F|FGHIJKLMNOPQRSTUVWXYZ. :/ABCDE
# G|GHIJKLMNOPQRSTUVWXYZ. :/ABCDEF
# H|HIJKLMNOPQRSTUVWXYZ. :/ABCDEFG
# I|IJKLMNOPQRSTUVWXYZ. :/ABCDEFGH
# J|JKLMNOPQRSTUVWXYZ. :/ABCDEFGHI
# K|KLMNOPQRSTUVWXYZ. :/ABCDEFGHIJ
# L|LMNOPQRSTUVWXYZ. :/ABCDEFGHIJK
# M|MNOPQRSTUVWXYZ. :/ABCDEFGHIJKL
# N|NOPQRSTUVWXYZ. :/ABCDEFGHIJKLM
# O|OPQRSTUVWXYZ. :/ABCDEFGHIJKLMN
# P|PQRSTUVWXYZ. :/ABCDEFGHIJKLMNO
# Q|QRSTUVWXYZ. :/ABCDEFGHIJKLMNOP
# R|RSTUVWXYZ. :/ABCDEFGHIJKLMNOPQ
# S|STUVWXYZ. :/ABCDEFGHIJKLMNOPQR
# T|TUVWXYZ. :/ABCDEFGHIJKLMNOPQRS
# U|UVWXYZ. :/ABCDEFGHIJKLMNOPQRST
# V|VWXYZ. :/ABCDEFGHIJKLMNOPQRSTU
# W|WXYZ. :/ABCDEFGHIJKLMNOPQRSTUV
# X|XYZ. :/ABCDEFGHIJKLMNOPQRSTUVW
# Y|YZ. :/ABCDEFGHIJKLMNOPQRSTUVWX
# Z|Z. :/ABCDEFGHIJKLMNOPQRSTUVWXY
# .|. :/ABCDEFGHIJKLMNOPQRSTUVWXYZ
#  | :/ABCDEFGHIJKLMNOPQRSTUVWXYZ.
# :|:/ABCDEFGHIJKLMNOPQRSTUVWXYZ.
# /|/ABCDEFGHIJKLMNOPQRSTUVWXYZ. :
